# Generated by Django 4.2.3 on 2023-08-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_entrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(max_length=650),
        ),
    ]
